const practice = [
{
    title : 'green_platforms',
    category : 'shoes',
    subcategory: 'heels',
    color : 'green',
    size : '8',
    material : 'silk',
    source : 'Simmi Shoes',
    brand: 'Simmi',
    tag : 'hard to walk in', 
    image : './resources/items/images/green_platforms.jpeg'
},
{
    title : 'brown_heels',
    category : 'shoes',
    subcategory: 'heels',
    color : 'brown',
    size : '8',
    material : 'plastic',
    source : 'Forever 21',
    brand: 'Forever 21',
    tag : 'easy to walk in, club-friendly',
    image : 'src/resources/items/images/brown_heels.jpeg'
},
{
    title: 'green_nikes',
    category : 'shoes',
    subcategory: 'sneakers',
    color : 'green',
    size : '8.5',
    material : 'leather',
    source : 'StockX',
    brand: 'Nike',
    tag : 'creases and cleans easily',
    image: 'src/resources/items/images/green_sneakers.jpeg'
},
{
    title: 'neon_clogs',
    category: 'shoes',
    subcategory: 'slippers',
    color: 'green',
    size: '7',
    material : 'foam',
    source: 'Oluolin',
    brand: 'Oluolin',
    tag: 'too small; only wear with long pants',
    image: 'src/resources/items/images/neon_clogs.jpeg'
},
{
    title: 'pink_heels',
    category: 'shoes',
    subcategory: 'heels',
    color: 'pink',
    size: '8',
    material: 'leather',
    source: 'Simmi Shoes',
    brand: 'Simmi Shoes',
    tag: 'loose straps',
    image: 'src/resources/items/images/pink_heels.jpeg'
},
{
    title: 'white_platforms',
    category: 'shoes',
    subcategory: 'heels',
    color: 'white',
    size: '8',
    material: 'leather',
    source: 'Forever 21',
    brand: 'Forever 21',
    tag: 'dog bite marks on left foot',
    image: 'src/resources/items/images/white_platforms.jpeg'
},
{
    title: 'wavy_crocs',
    category: 'shoes',
    subcategory: 'slippers',
    color: 'green',
    size: '8',
    material: 'foam',
    source: 'StockX',
    brand: 'Crocs',
    tag: 'must wear with thick, long socks',
    image: 'src/resources/items/images/wavy_crocs.jpeg'
},
{
    title: 'chunky_boots',
    category: 'shoes',
    subcategory: 'boots',
    color: 'black',
    size: '8',
    material: 'leather',
    source: 'Simmi Shoes',
    brand: 'Simmi',
    tag: 'top part is stiff, wear with long socks',
    image: 'src/resources/items/images/chunky_boots.jpeg'
},
{
    title: 'forest_green_NB',
    category: 'shoes',
    subcategory: 'sneakers',
    color: 'green',
    size: '8',
    material: 'suede',
    source: 'StockX',
    brand: 'Nike',
    tag: 'looks great with gold anklet',
    image: 'src/resources/items/images/forest_green_sneakers.jpeg'
},
{
    title: 'blue_jordans',
    category: 'shoes',
    subcategory: 'sneakers',
    color: 'blue',
    size: '8.5',
    material: 'leather',
    source: 'Good Times Charlotte',
    brand: 'Nike',
    tag: '',
    image: 'src/resources/items/images/blue_jordans.jpeg'
},
{
    title: 'light_jeans',
    category: 'bottoms',
    subcategory: 'pants',
    color: 'blue',
    size: '6',
    material: 'denim',
    source: 'American Eagle',
    brand: 'American Eagle',
    tag: 'super comfy! perfect length',
    image: 'src/resources/items/images/light_jeans.jpeg'
},
{
    title: 'navy_cargos',
    category: 'bottoms',
    subcategory: 'pants',
    color: 'blue',
    size: '6',
    material: 'cotton',
    source: 'American Eagle',
    brand: 'American Eagle',
    tag: 'shrinks in the wash',
    image: 'src/resources/items/images/navy_cargos.jpeg'
}, 
{
    title: 'edgy_miniskirt',
    category: 'bottoms',
    subcategory: 'skirt',
    color: 'black',
    size: 'S',
    material: 'denim',
    source: 'Urban Outfitters',
    brand: '',
    tag: 'stretchy! super short',
    image: 'src/resources/items/images/edgy_miniskirt.jpeg'
},
{
    title: 'velvet_flare_pants',
    category: 'bottoms',
    subcategory: 'pants',
    color: 'green',
    size: 'S',
    material: 'velvet',
    source: 'Shein',
    brand: 'Shein',
    tag: 'better with platforms. keep it groovy!',
    image: 'src/resources/items/images/velvet_flare_pants'
}, 
{
    title: 'black_jeans',
    category: 'bottoms',
    subcategory: 'pants',
    color: 'black',
    size: 'M',
    material: 'denim',
    source: 'Forever 21',
    brand: 'Forever 21',
    tag: 'tight around hips, need a belt',
    image: 'src/resources/items/images/black_jeans',
},
{
    title: 'corduroy_jacket',
    category: 'outerwear',
    subcategory: 'jacket',
    color: 'blue',
    size: 'L',
    material: 'corduroy',
    source: 'Forever 21',
    brand: 'Forever 21',
    tag: 'very warm, perfect for layering',
    image: 'src/resources/items/images/corduroy_jacket'
},
{
    title: 'levis_jacket',
    category: 'outerwear',
    subcategory: 'jacket',
    color: 'blue',
    size: 'L',
    material: 'denim',
    source: 'found at a party',
    brand: 'Levis',
    tag: 'collar is twisted, but a cool rugged look',
    image: 'src/resources/items/images/levis_jacket'
},
{
    title: 'blue_windbreaker',
    category: 'outerwear',
    subcategory: 'jacket',
    color: 'blue',
    size: 'L',
    material: 'swishy',
    source: 'Goodwill',
    brand: 'Nike',
    tag: 'very thin, adjustable scrunch along the hem',
    image: 'src/resources/items/images/blue_windbreaker'
},
{
    title: 'stranger_holiday_sweater',
    category: 'tops',
    subcategory: 'sweater',
    color: 'blue',
    size: 'M',
    material: 'knit',
    source: 'Target',
    brand: '',
    tag: 'comfy convo starter',
    image: 'src/resources/items/images/stranger_holiday_sweater.jpeg'
},
{
    title: 'bape_croptop',
    category: 'tops',
    subcategory: 't-shirt',
    color: 'white',
    size: 'S',
    material: 'cotton',
    source: 'Stolen from my ex',
    brand: 'Bape',
    tag: 'armpit stains!',
    image: 'src/resources/items/images/bape_croptop.jpeg'
},
{
    title: 'criss_cross_crop',
    category: 'tops',
    subcategory: 'shirt',
    color: 'white',
    size: 'S',
    material: 'knit',
    source: 'Forever 21',
    brand: 'Forever 21',
    tag: 'untrustworthy; should not lift arms too high',
    image: 'src/resources/items/images/criss_cross_crop',
}, 
{
    title: 'off_shoulder_crop',
    category: 'tops',
    subcategory: 'shirt',
    color: 'black',
    size: 'S',
    material: 'knit',
    source: 'Forever 21',
    brand: 'Forever 21',
    tag: 'extremely cropped',
    image: 'src/resources/items/images/off_shoulder_crop.jpeg'
},
{
    title: 'ribbed_tank',
    category: 'tops',
    subcategory: 'shirt',
    color: 'black',
    size: 'S',
    material: 'stretch',
    source: 'Forever 21',
    brand: 'Forever 21',
    tag: 'the comfiest',
    image: 'src/resources/items/images/ribbed_tank.jpeg'
},
{
    title: 'chocolate_swirl_skirt',
    category: 'bottoms',
    subcategory: 'skirt',
    color: 'brown',
    size: 'M',
    material: 'polyester',
    source: 'Shein',
    brand: 'Shein',
    tag: 'kinda loose, need to fold waistband a few times',
    image: 'src/resources/items/images/chocolate_swirl_skirt.jpeg'
},
{
    title: 'blessing_tee',
    category: 'tops',
    subcategory: 't-shirt',
    color: 'black',
    size: 'S',
    material: 'cotton',
    source: 'God is Dope Brand',
    brand: 'Gos is Dope',
    tag: 'bleach stain near bottom',
    image: 'src/resources/items/images/blessing_tee.jpeg'
}, 
{
    title: 'high_life_tee',
    category: 'tops',
    subcategory: 't-shirt',
    color: 'green',
    size: 'M',
    material: 'cotton',
    source: 'Stole from my ex',
    brand: 'High Life',
    tag: 'comfy',
    image: 'src/resources/items/images/high_life_tee.jpeg'
},
{
    title: 'camo_graphic_tee',
    category: 'tops',
    subcategory: 't-shirt',
    color: 'brown',
    size: 'M',
    material: 'cotton',
    source: 'Loved By Her Brand',
    brand: 'Loved By Her',
    tag: 'bright orange detail on back',
    image: 'src/resources/items/images/camo_graphic_tee.jpeg'
},
{
    title: 'bye_felicia_tee',
    category: 'tops',
    subcategory: 't-shirt',
    color: 'black',
    size: 'L',
    material: 'cotton',
    source: 'Zumiez',
    brand: 'DGK',
    tag: 'kinda long',
    image: 'src/resources/items/images/bye_felicia_tee.jpeg'
},
{
    title: 'pink_halter_dress',
    category: 'tops',
    subcategory: 'dress',
    color: 'pink',
    size: 'S',
    material: 'beachtowel',
    source: 'Target',
    brand: '',
    tag: '',
    image: 'src/resources/items/images/pink_halter_dress.jpeg'
},
{
    title: 'green_maxi_dress',
    category: 'tops',
    subcategory: 'dress',
    color: 'green',
    size: 'M',
    material: 'stretchy',
    source: 'Parade Brand',
    brand: 'Parade',
    tag: 'gets stretched quick',
    image: 'src/resources/items/images/green_maxi_dress'
},
{
    title: 'floral_shirt_dress',
    category: 'tops',
    subcategory: 'dress',
    color: 'yellow',
    size: 'S',
    material: 'polyester',
    source: 'Ann Taylor',
    brand: 'Ann Taylor',
    tag: 'interview',
    image: 'src/resources/items/images/floral_shirt_dress.jpeg'
},
{
    title: 'schoolgirl_skirt',
    category: 'bottoms',
    subcategory: 'skirt',
    color: 'blue',
    size: 'M',
    material: 'polyester',
    source: 'H&M',
    brand: 'H&M',
    tag: 'plaid with pleats',
    image: 'src/resources/items/images/schoolgirl_skirt.jpeg'
},
{
    title: 'orange_LA_cap',
    category: 'accessory',
    color: 'orange',
    size: '',
    material: '',
    source: 'Urban Outfitters',
    brand: '47 Brand',
    tag: 'casual',
    image: 'src/resources/items/images/orange_LA_cap.jpeg'
},
{
    title: 'trippy_trucker_hat',
    category: 'accessory',
    color: 'black',
    size: '',
    material: '',
    source: 'Urban Outfitters',
    brand: '',
    tag: 'casual',
    image: 'src/resources/items/images/trippy_trucker_hat.jpeg'
},
{
    title: 'PBW_bag',
    category: 'accessory',
    color: 'pink',
    size: 'M',
    material: 'faux leather',
    source: 'CISE',
    brand: 'CISE',
    tag: '',
    image: 'src/resources/items/images/PBW_bag.jpeg'
}, 
{
    title: 'mini_telfar',
    category: 'accessory',
    color: 'black',
    size: 'S',
    material: 'leather',
    source: 'Telfar',
    brand: 'Telfar',
    tag: 'versatile',
    image: 'src/resources/items/images/mini_telfar.jpeg'
}, 
{
    title: 'green_banded_purse',
    category: 'accessory',
    color: 'green',
    size: 'S',
    material: 'leather',
    source: 'Shein',
    brand: '',
    tag: 'gold accents',
    image: 'src/resources/items/images/green_banded_purse.jpeg'
},
{
    title: 'gator_purse',
    category: 'accessory',
    color: 'black',
    size: 'S',
    material: 'faux alligator',
    source: 'Shein',
    brand: '',
    tag: '',
    image: 'src/resources/items/images/gator_purse'
}
]
export default practice